<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace GPBMetadata;

class Product
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
à
product.protopb.mall"z
Product

id (
name (	
desc (	
stock (
amount (
create_time (	
update_time (	"
ProductIdRequest

id ("4
ProductResponse!
product (2.pb.mall.Product2X
ProductServiceF
FindProductById.pb.mall.ProductIdRequest.pb.mall.ProductResponseBZinternal/mall/pbbproto3'
        , true);

        static::$is_initialized = true;
    }
}

