<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Pb\Mall;

/**
 * Protobuf type <code>pb.mall.ProductService</code>
 */
interface ProductServiceInterface
{
    /**
     * Method <code>findProductById</code>
     *
     * @param \Pb\Mall\ProductIdRequest $request
     * @return \Pb\Mall\ProductResponse
     */
    public function findProductById(\Pb\Mall\ProductIdRequest $request);

}

