<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Pb\Mall;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pb.mall.ProductResponse</code>
 */
class ProductResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.pb.mall.Product product = 1;</code>
     */
    protected $product = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Pb\Mall\Product $product
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Product::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.pb.mall.Product product = 1;</code>
     * @return \Pb\Mall\Product|null
     */
    public function getProduct()
    {
        return $this->product;
    }

    public function hasProduct()
    {
        return isset($this->product);
    }

    public function clearProduct()
    {
        unset($this->product);
    }

    /**
     * Generated from protobuf field <code>.pb.mall.Product product = 1;</code>
     * @param \Pb\Mall\Product $var
     * @return $this
     */
    public function setProduct($var)
    {
        GPBUtil::checkMessage($var, \Pb\Mall\Product::class);
        $this->product = $var;

        return $this;
    }

}

